name: Zip Folders

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger this on
  workflow_dispatch: # Allows manual trigger

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip DataPacks folder
        run: |
          zip -r DataPack.zip DataPack

      - name: Zip ResourcePacks folder
        run: |
          zip -r ResourcePack.zip ResourcePack
          
      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zipped-folders
          path: |
            DataPacks.zip
            ResourcePacks.zip
