name: Zip DataPack and ResourcePack

on:
  push:
    branches:
      - main  # Trigger on push to the main branch, change to your target branch
  workflow_dispatch:  # Allow manual trigger from the GitHub Actions UI

jobs:
  zip-folders:
    runs-on: ubuntu-latest  # Use a Linux runner (Ubuntu) for this job

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install zip (if not already installed)
    - name: Install zip
      run: sudo apt-get install zip

    # Step 3: Zip the DataPack and ResourcePack folders
    - name: Zip DataPack and ResourcePack
      run: |
        zip -r DataPack.zip DataPack/
        zip -r ResourcePack.zip ResourcePack/

    # Step 4: Upload the zipped files as artifacts (optional)
    - name: Upload zipped files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zipped-files
        path: |
          DataPack.zip
          ResourcePack.zip
